[package]
name = "nessuno"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bdf-parser = "0.1.0"
bincode = "1.3.3"
clap = { version = "3.2.13", features = ["derive"] }
cpal = "0.13.5"
crossbeam-channel = "0.5.5"
directories = "4.0.1"
flate2 = "1.0.24"
gilrs = "0.9.0"
pixels = "0.9.0"
serde = "1.0.140"
serde-big-array = "0.4.1"
typetag = "0.2.1"
winit = "0.26.1"
winit_input_helper = "0.12.0"
