[package]
name = "nessuno"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bdf-parser = "0.1.0"
bincode = "1.3.3"
clap = { version = "4.1.6", features = ["derive"] }
cpal = "0.15.0"
crossbeam-channel = "0.5.6"
directories = "4.0.1"
flate2 = "1.0.25"
gilrs = "0.10.1"
ips = "0.1.0"
pixels = "0.11.0"
serde = "1.0.152"
serde-big-array = "0.5.0"
serde-xml-rs = "0.6.0"
sha1_smol = "1.0.0"
typetag = "0.2.5"
winit = "0.28.1"
winit_input_helper = "0.14.0"

[profile.release]
lto = true
