[package]
name = "nessuno"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bdf-parser = "0.1.0"
env_logger = "0.9.0"
log = "0.4.14"
pixels = "0.9.0"
winit = "0.26.0"
winit_input_helper = "0.11.0"
