[package]
name = "nessuno"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bdf-parser = { git = "https://github.com/embedded-graphics/bdf", rev = "a880098dae12ac279976736bd806b59eb3aba782" }
bincode = "1.3.3"
clap = { version = "4.4.6", features = ["derive"] }
cpal = "0.15.2"
crossbeam-channel = "0.5.8"
directories = "5.0.1"
flate2 = "1.0.27"
gilrs = "0.10.2"
ips = { path = "./ips" }
pixels = "0.13.0"
serde = "1.0.188"
serde-big-array = "0.5.1"
serde-xml-rs = "0.6.0"
sha1_smol = "1.0.0"
typetag = "0.2.13"
winit = "0.28.7"
winit_input_helper = "0.14.1"

[profile.release]
lto = true
